name: Show Last README Update Time
run-name: Checking for readme on push
on:
  push:
    branches:
      - 1149-am-test-branch

jobs:
  show_last_update_time:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch README Content
        id: fetch_readme
        run: |
          readme_content=$(curl -s -H "Accept: application/vnd.github.v3+json" https://raw.githubusercontent.com/${{ github.repository }}/main/README.md)
          echo "::set-output name=readme_content::$readme_content"

      - name: Extract Last Updated Time
        id: extract_time
        run: |
          last_updated=$(echo "${{ steps.fetch_readme.outputs.readme_content }}" | grep -oP '^Last updated: \K.*')
          echo "::set-output name=last_updated::$last_updated"

      - name: Show Last Update Time
        run: |
          echo "Last README update time: ${{ steps.extract_time.outputs.last_updated }}"
