# name: Check README Update on main
# run-name: 10 min README update yes/no?
# on:
#   schedule:
#       - cron: '*/10 * * * *' # Triggered every 10 minutes

# jobs:
#   check_readme_update:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Fetch Previous README Content
#         id: fetch_prev_readme
#         run: |
#           prev_readme_content=$(curl -sSL "https://raw.githubusercontent.com/${{ github.repository }}/main/README.md")
#           echo "::set-output name=prev_readme_content::$prev_readme_content"

#       - name: Fetch Current README Content
#         id: fetch_curr_readme
#         run: |
#           curr_readme_content=$(curl -sSL "https://raw.githubusercontent.com/${{ github.repository }}/main/README.md")
#           echo "::set-output name=curr_readme_content::$curr_readme_content"

#       - name: Compare READMEs
#         id: compare_readmes
#         run: |
#           diff -u <(echo "${{ steps.fetch_prev_readme.outputs.prev_readme_content }}") <(echo "${{ steps.fetch_curr_readme.outputs.curr_readme_content }}") || true
#           echo "::set-output name=readme_updated::${PIPESTATUS[0]}"

#       - name: Notify if README Updated
#         if: steps.compare_readmes.outputs.readme_updated != 0
#         run: echo "README file was updated on test-branch-1!"
name: Check README Update

on:
  schedule:
    - cron: '*/10 * * * *'  # Trigger every 10 minutes

jobs:
  check_readme_update:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Previous README Content
        id: fetch_prev_readme
        run: |
          prev_readme_content=$(curl -sSL "https://raw.githubusercontent.com/${{ github.repository }}/main/README.md")
          echo "::set-output name=prev_readme_content::$prev_readme_content"

      - name: Fetch Current README Content
        id: fetch_curr_readme
        run: |
          curr_readme_content=$(curl -sSL "https://raw.githubusercontent.com/${{ github.repository }}/main/README.md")
          echo "::set-output name=curr_readme_content::$curr_readme_content"

      - name: Compare READMEs
        id: compare_readmes
        run: |
          diff -u <(echo "${{ steps.fetch_prev_readme.outputs.prev_readme_content }}") <(echo "${{ steps.fetch_curr_readme.outputs.curr_readme_content }}") || true
          echo "::set-output name=readme_updated::${PIPESTATUS[0]}"

      - name: Dispatch README Update Event
        if: steps.compare_readmes.outputs.readme_updated != 0
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.repos.createDispatchEvent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              event_type: 'readme_updated'
            })
