name: Re-named Issue Comment Handler
run-name: Issue Comment made by ${{github.actor}}
on:
  issue_comment:
    types: [created, deleted]

jobs:
  handle_comment:
    runs-on: ubuntu-latest
    steps:
      - name: Alert Action For Comment
        uses: actions/github-script@v6
        with:
          script: |
            console.log(context.payload.comment.body);
            console.log(context.payload.comment.user.login);
