name: Issue Open Action
run-name: An issue was opened by ${{ github.actor }} 
  issues:
    types: [opened]

jobs:
  handle_comment:
    runs-on: ubuntu-latest
    steps:
      - name: Alert Action for opened or closed issue
        uses: actions/github-script@v7
        with:
          script: |
            console.log(context.payload.issue.body);
            console.log(context.payload.issue.user.login);
