name: Issue Closed Action
run-name: An issue was closed by ${{ github.actor }} 
on:
  issues:
    types: [closed]

jobs:
  handle_comment:
    runs-on: ubuntu-latest
    steps:
      - name: Alert Action for closed issue
        uses: actions/github-script@v7
        with:
          script: |
            console.log(context.payload.issue.body);
            console.log(context.payload.issue.user.login);
