name: Issue Creation or Deletion Action
run-name: ${{ github.actor }} opened or closed an issue
on:
  issues:
    types: [opened, closed]

jobs:
  handle_comment:
    runs-on: ubuntu-latest
    steps:
      - name: Alert Action for opened or closed issue
        uses: actions/github-script@v7
        with:
          script: |
            console.log(context.payload.issue.body);
            console.log(context.payload.issue.user.login);
