name: Issue Creation Action

on:
  issues:
    types: [opened]

jobs:
  handle_comment:
    runs-on: ubuntu-latest
    steps:
      - name: Alert Action For Comment
        uses: actions/github-script@v6
        with:
          script: |
            console.log(context.payload.issue.body);
            console.log(context.payload.issue.user.login);
