name: Pull Request Merged Alert
run-name: A merge request was approved by ${{ github.actor }}
on:
  pull_request:
    types: [closed]

jobs:
  handle_merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Alert Step Action for Pull Request Merge
        uses: actions/github-script@v7
        with:
          script: |
            console.log("Pull request merged!");
            console.log("Pull Request Title:", context.payload.pull_request.title);
            console.log("Pull Request Number:", context.payload.pull_request.number);
            console.log("Merged By:", context.payload.pull_request.user.login);
